baseURL = 'https://example.org/'
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn" # en / zh-cn / ... (This field determines which i18n file to use)
title = '活死人の行知路'
# 启用主题
theme = 'hugo-theme-drone'

[author]
  name = "活死人"

[outputs]
  home = ["HTML", "RSS", "JSON"]

# 新增分页配置
[pagination]
    pagerSize = 20

# ==========================================
# 站点自定义参数 (Params) - 全部平铺
# ==========================================
[params]
  # 站点基础信息
  logoTitle = "虽千万里，吾往矣"
  keywords = ["Hugo", "theme", "drone"]
  description = "遥望未来一片混沌；纵前路漫漫，既心之所向 虽千万里，吾往矣"
  avatar = "/images/avatar.png"
  logo = "/images/avatar.png"
  # 首页 Photo Card 展示的图片路径
  home_photo_url = "/images/cat.png"
  # 备案信息
  icp = "苏ICP备20013139号-2"
  # 开启文章图片点击放大 (Lightbox)
  enableImageZoom = true
  [params.author]
    name = "活死人"

[[menu.main]]
    name = "笔记"
    title = "笔记"
    weight = 1
    identifier = "posts"
    url = "/posts"
    params = { icon = "scroll" }  # 修改这里：显式定义 params
[[menu.main]]
    name = "悦❤️读"
    title = "悦❤️读"
    weight = 2
    identifier = "reading"
    url = "/reading/mine"
    params = { icon = "book" }
[[menu.main]]
    name = "行知路"
    title = "行知路"
    weight = 3
    identifier = "moments"
    url = "/journey/moments"
    params = { icon = "website" }
[[menu.main]]
    name = "我的项目"
    title = "我的项目"
    weight = 4
    identifier = "projects"
    url = "/projects"
    params = { icon = "projects" }
[[menu.main]]
    name = "效率工具"
    title = "效率工具"
    weight = 5
    identifier = "tools"
    url = "/tools"
    params = { icon = "tools" }
[[menu.main]]
    name = "关于"
    title = "关于"
    weight = 6
    identifier = "about"
    url = "/about"
    params = { icon = "about" }


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 4  # 这里必须改为 4 或更高
