baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

theme = 'hugo-theme-drone'

[author]
    name = "活死人"

[params]
    # 站点信息（可选，不需要的可以直接注释掉）
    logoTitle = "活死人"                                   # 默认值: 上面设置的title值
    keywords = ["Hugo", "theme","drone"]
    description = "遥望未来，一片混沌，行知路，虽千万里，吾往矣"

    # 首页 Photo Card 展示的图片路径
    home_photo_url = "/images/cat.png"

[params.meta]
        username = "Y"
        avatar = "/images/avatar.png"
        description = "活死人の行知路..."

[[menu.main]]
    name = "笔记"
    title = "笔记"
    weight = 1
    identifier = "posts"
    url = "/posts"
    params = { icon = "scroll" }  # 修改这里：显式定义 params
[[menu.main]]
    name = "悦❤️读"
    title = "悦❤️读"
    weight = 2
    identifier = "reading"
    url = "/reading/mine"
    params = { icon = "book" }
[[menu.main]]
    name = "行知路"
    title = "行知路"
    weight = 3
    identifier = "moments"
    url = "/journey/moments"
    params = { icon = "website" }
[[menu.main]]
    name = "我的项目"
    title = "我的项目"
    weight = 4
    identifier = "projects"
    url = "/projects"
    params = { icon = "projects" }
[[menu.main]]
    name = "效率工具"
    title = "效率工具"
    weight = 5
    identifier = "tools"
    url = "/tools"
    params = { icon = "tools" }
[[menu.main]]
    name = "关于"
    title = "关于"
    weight = 6
    identifier = "about"
    url = "/about"
    params = { icon = "about" }